# Build the rock
name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Get name
        id: name
        run: echo "name=$(yq '.name' rockcraft.yaml)" >> "$GITHUB_OUTPUT"

      - uses: canonical/craft-actions/rockcraft-pack@main
        id: rockcraft

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      - name: Create SBOM
        run: syft ${{ steps.rockcraft.outputs.rock }} -o spdx-json=${{ steps.name.outputs.name }}.sbom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ steps.name.outputs.name }}-sbom
          path: "${{ steps.name.outputs.name }}.sbom.json"

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: rock
          path: ${{ steps.rockcraft.outputs.rock }}
